---
10.20.30.122:
  city: null
  country: null
  hostname: null
  last_used_at: '2020-02-02T22:19:54.744176+00:00'
  prev_used_at: null
  region: null
  user_id: 2e7c88224ab84431b1775ae7cda9c9fe
  username: Sebastian
10.20.30.20:
  city: null
  country: null
  hostname: N550JV
  last_used_at: '2020-04-12T15:14:25.671122+00:00'
  prev_used_at: '2020-04-12T14:41:53.789741+00:00'
  region: null
  user_id: 2e7c88224ab84431b1775ae7cda9c9fe
  username: Sebastian
10.20.30.22:
  city: null
  country: null
  hostname: null
  last_used_at: '2020-04-09T20:20:00.209402+00:00'
  prev_used_at: null
  region: null
  user_id: 2e7c88224ab84431b1775ae7cda9c9fe
  username: Sebastian
10.20.30.23:
  city: null
  country: null
  hostname: null
  last_used_at: '2020-04-11T23:25:27.437026+00:00'
  prev_used_at: null
  region: null
  user_id: 2e7c88224ab84431b1775ae7cda9c9fe
  username: Sebastian
155.91.64.17:
  city: London
  country: United Kingdom
  hostname: null
  last_used_at: '2019-10-30T10:43:50.854031+00:00'
  prev_used_at: null
  region: England
  user_id: 2e7c88224ab84431b1775ae7cda9c9fe
  username: Sebastian
172.30.32.2:
  city: null
  country: null
  hostname: supervisor.local.hass.io
  last_used_at: '2020-04-12T14:47:13.775937+00:00'
  prev_used_at: '2020-04-11T17:44:07.390850+00:00'
  region: null
  user_id: acfd93cdf2be4e10b5d8f331ea19998b
  username: Hass.io
172.30.33.5:
  city: null
  country: null
  hostname: null
  last_used_at: '2020-03-25T00:02:01.190945+00:00'
  prev_used_at: null
  region: null
  user_id: 2e7c88224ab84431b1775ae7cda9c9fe
  username: Sebastian
83.208.69.41:
  city: Smecno
  country: Czechia
  hostname: null
  last_used_at: '2019-11-10T07:49:22.046842+00:00'
  prev_used_at: null
  region: Central Bohemia
  user_id: 2e7c88224ab84431b1775ae7cda9c9fe
  username: Sebastian
90.180.50.29:
  city: Cernosice
  country: Czechia
  hostname: null
  last_used_at: '2020-01-02T08:45:20.161409+00:00'
  prev_used_at: null
  region: Central Bohemia
  user_id: 2e7c88224ab84431b1775ae7cda9c9fe
  username: Sebastian
