- id: '1567199368534'
  alias: HA recovers after power outage - turn off all lights
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - condition: state
    entity_id: input_boolean.maintenance_mode
    state: 'off'
  action:
  - data:
      entity_id: group.all_lights
    entity_id: group.all_lights
    service: light.turn_off
  - data:
      message: Home Assistant started after unexpected shutdown.
      title: Home Assistant started
    service: notify.telegram
  - delay: 00:00:10
- id: '1567201768135'
  alias: HA manual restart - enter maintenance mode
  trigger:
  - event: shutdown
    platform: homeassistant
  action:
  - data:
      entity_id: input_boolean.maintenance_mode
    entity_id: input_boolean.maintenance_mode
    service: input_boolean.turn_on
  - delay: 00:00:05
