- id: '1568108501657'
  alias: Freezer opened
  trigger:
  - entity_id: binary_sensor.openclose_10
    for: 00:02:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Freezer is opened
    service: telegram_bot.send_message
- id: '1568110065705'
  alias: Water sensor
  trigger:
  - entity_id: binary_sensor.water_5
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.water_6
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Water sensor triggered!
    service: telegram_bot.send_message
- id: '1568107310243'
  alias: Entrance door opened
  trigger:
  - entity_id: binary_sensor.openclose_11
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.sebastian
    state: not_home
  action:
  - data:
      message: Entrance door opened!
      title: Burglary alarm
    service: telegram_bot.send_message
- id: '1567199368534'
  alias: HA recovers after power outage - turn off all lights
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - condition: state
    entity_id: input_boolean.maintenance_mode
    state: 'off'
  action:
  - delay: 00:00:30
  - service: light.turn_off
    data:
      entity_id: group.bulbs
  - service: notify.telegram
    data:
      message: Home Assistant started after unexpected shutdown.
      title: Home Assistant started
- id: heating_morning_on_wd
  alias: heating - weekday morning
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == ( state_attr(''input_datetime.weekday_start'',
      ''timestamp'') | int | timestamp_custom(''%H:%M'', False) ) }}'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: input_boolean.heating_timer
    state: 'on'
  - condition: state
    entity_id: person.sebastian
    state: home
  action:
  - data_template:
      entity_id: climate.room_heating
      temperature: '{{ states(''input_number.target_temp_room_high'') }}'
    service: climate.set_temperature
  - data_template:
      entity_id: climate.bathroom_heating
      temperature: '{{ states(''input_number.target_temp_bathroom_high'') }}'
    service: climate.set_temperature
- id: heating_evening_off_wd
  alias: heating - weekday night
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == ( state_attr(''input_datetime.weekday_end'',
      ''timestamp'') | int | timestamp_custom(''%H:%M'', False) ) }}'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: input_boolean.heating_timer
    state: 'on'
  - condition: state
    entity_id: person.sebastian
    state: home
  action:
  - data_template:
      entity_id: climate.room_heating
      temperature: '{{ states(''input_number.target_temp_room_low'') }}'
    service: climate.set_temperature
- id: heating_morning_on_we
  alias: heating - weekend morning
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == ( state_attr(''input_datetime.weekend_start'',
      ''timestamp'') | int | timestamp_custom(''%H:%M'', False) ) }}'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  - condition: state
    entity_id: input_boolean.heating_timer
    state: 'on'
  - condition: state
    entity_id: person.sebastian
    state: home
  action:
  - data_template:
      entity_id: climate.room_heating
      temperature: '{{ states(''input_number.target_temp_room_high'') }}'
    service: climate.set_temperature
  - data_template:
      entity_id: climate.bathroom_heating
      temperature: '{{ states(''input_number.target_temp_bathroom_high'') }}'
    service: climate.set_temperature
- id: heating_evening_off_we
  alias: heating - weekend night
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == ( state_attr(''input_datetime.weekend_end'',
      ''timestamp'') | int | timestamp_custom(''%H:%M'', False) ) }}'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  - condition: state
    entity_id: input_boolean.heating_timer
    state: 'on'
  - condition: state
    entity_id: person.sebastian
    state: home
  action:
  - data_template:
      entity_id: climate.room_heating
      temperature: '{{ states(''input_number.target_temp_room_low'') }}'
    service: climate.set_temperature
  - data_template:
      entity_id: climate.bathroom_heating
      temperature: '{{ states(''input_number.target_temp_bathroom_low'') }}'
    service: climate.set_temperature
- id: heating_on_when_home
  alias: heating - turn heating on on arrival
  trigger:
  - entity_id: person.sebastian
    from: not_home
    platform: state
    to: home
  action:
  - data:
      preset_mode: none
    service: climate.set_preset_mode
  - data_template:
      entity_id: climate.bathroom_heating
      temperature: '{{ states(''input_number.target_temp_bathroom_low'') }}'
    service: climate.set_temperature
- id: heating_off_when_away
  alias: heating - turn off when we leave home
  trigger:
  - entity_id: person.sebastian
    for: 00:10:00
    from: home
    platform: state
    to: not_home
  action:
  - data:
      preset_mode: away
    service: climate.set_preset_mode
- id: '1570365018863'
  alias: heating - kitchen on
  trigger:
  - platform: template
    value_template: '{{ (state_attr(''climate.room_heating'', ''temperature'') | float)
      - (states(''sensor.temperature_2'') | float) > 1.0}}'
  condition: []
  action:
  - device_id: b95dc98ae71941c68e4f32961e25ae2a
    domain: switch
    entity_id: switch.ikea_plug_2
    type: turn_on
- id: '1570365069845'
  alias: heating - kitchen off
  trigger:
  - platform: template
    value_template: '{{ (state_attr(''climate.room_heating'', ''temperature'') | float)
      - (states(''sensor.temperature_2'') | float) < 0.5 }}'
  condition: []
  action:
  - device_id: b95dc98ae71941c68e4f32961e25ae2a
    domain: switch
    entity_id: switch.ikea_plug_2
    type: turn_off
- id: '1570130746943'
  alias: remote bedroom bulb
  trigger:
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_short_press
  - device_id: 977ed79430444f9dab60df1c7035c4fd
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_short_press
  condition: []
  action:
  - device_id: 25225d38879b423397fe3c8d11e5a218
    domain: light
    entity_id: light.ikea_bulb_2
    type: toggle
- id: '1570212713167'
  alias: remote living room bulb
  trigger:
  - device_id: 977ed79430444f9dab60df1c7035c4fd
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_short_press
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_short_press
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_short_press
  condition: []
  action:
  - device_id: e3fba55eeae242c18065b69127fcf46f
    domain: light
    entity_id: light.ikea_bulb_1
    type: toggle
- id: '1570213166105'
  alias: remote standing lamp switch
  trigger:
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_long_press
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_long_press
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.08102185a4cf12a83367
    service: switch.toggle
- id: '1570214150331'
  alias: remote desk lamp switch
  trigger:
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_long_press
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: right
    type: remote_button_long_press
  condition: []
  action:
  - data:
      entity_id: switch.08102185a4cf12a8361f
    service: switch.toggle
- id: '1570214365100'
  alias: remote bathroom bulb
  trigger:
  - device_id: 938fddfde7134636aa05d12b4f4df16b
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_short_press
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_short_press
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_short_press
  condition: []
  action:
  - device_id: b2fc53cb967544afaa64c50b48b95840
    domain: light
    entity_id: light.osram_bulb_1
    type: toggle
- id: '1570215042351'
  alias: remote ceiling light switch
  trigger:
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_long_press
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_long_press
  condition: []
  action:
  - device_id: b79bdaab2df4423e82938a62556d1db6
    domain: light
    entity_id: light.cable_onoff_2
    type: toggle
- id: '1570215199936'
  alias: remote hood switch
  trigger:
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - device_id: d964f0b9e6c64edd91d313b1d18f7434
    domain: light
    entity_id: light.cable_onoff
    type: toggle
- id: '1570215295449'
  alias: remote sink lamp switch
  trigger:
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_long_press
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_long_press
  condition: []
  action:
  - device_id: a5eff051123d4f848250fd350f95d86b
    domain: switch
    entity_id: switch.osram_plug_1
    type: toggle
- id: '1570219780878'
  alias: remote oven switch
  trigger:
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_long_press
  condition: []
  action:
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_short_press
- id: '1570225511440'
  alias: remote mirror lamp switch
  trigger:
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_long_press
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: left
    type: remote_button_long_press
  condition: []
  action:
  - device_id: 3ffe83ae8d374484ab3f3f4bf93e7506
    domain: switch
    entity_id: switch.osram_plug_3
    type: toggle
- id: '1570405317272'
  alias: heating - bathroom switch turned off
  trigger:
  - entity_id: switch.osram_plug_4
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data_template:
      entity_id: climate.bathroom_heating
      temperature: '{{ states(''input_number.target_temp_bathroom_low'') }}'
    service: climate.set_temperature
- id: '1570484180533'
  alias: remote cooling
  trigger:
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.081021853c71bf3edb01
    service: switch.toggle
- id: '1570485402465'
  alias: 'heating - notify ceiling switched on '
  trigger:
  - entity_id: switch.ikea_plug
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Ceiling heating panel turned on
    service: notify.html5
- id: '1570485651434'
  alias: heating - notify ceiling switched off
  trigger:
  - entity_id: switch.ikea_plug
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Ceiling heating panel switched off
    service: notify.html5
- id: '1570485730562'
  alias: heating - notify wall panel switched on
  trigger:
  - entity_id: switch.ikea_plug_2
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Heating wall panel switched on
    service: notify.html5
- id: '1570486021472'
  alias: heating - notify wall panel switched off
  trigger:
  - entity_id: switch.ikea_plug_2
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Wall heating panel turned off
    service: notify.html5
- id: '1570486105628'
  alias: heating - notify radiator turned on
  trigger:
  - entity_id: switch.osram_plug_4
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Bathroom radiator turned on
    service: notify.html5
- id: '1570486156080'
  alias: heating - notify radiator turned off
  trigger:
  - entity_id: switch.osram_plug_4
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Bathroom radiator turned off
    service: notify.html5
- id: '1570606700515'
  alias: remote - entrance bulb
  trigger:
  - device_id: 938fddfde7134636aa05d12b4f4df16b
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  - device_id: 5617d4f82ce941e8bae8728066a1a1a5
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_short_press
  - device_id: b0ca211ba3364ecd8a2d0540b9a371ff
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_short_press
  condition: []
  action:
  - device_id: ef2cce166005498b9b4a731b6bd01c3b
    domain: light
    entity_id: light.osram_bulb_2
    type: toggle
