default_config:

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml

frontend:
  themes: !include themes.yaml

logger:
  default: warning
history:
recorder:
  db_url: sqlite:////tmp/home-assistant_v2.db
  exclude:
    entities:
    - sensor.time

sensor:
  - platform: time_date
    display_options:
      - 'time'

ios:

tuya:
  username: !secret tuya_login
  password: !secret tuya_password
  country_code: 420
  platform: smart_life

google_assistant:
  project_id: !secret google_assistant_id
  entity_config:
    group.all_automations:
      expose: false

notify:
  - name: html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - name: all
    platform: group
    services:
      - service: html5
      - service: ios_i7sw
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

asuswrt:
  host: !secret asuswrt_host
  username: !secret asuswrt_username
  ssh_key: /ssl/asuswrt_ssh
  sensors:
    - download_speed
    - upload_speed

climate:
  - platform: generic_thermostat
    name: Room Heating
    heater: switch.ikea_plug
    target_sensor: sensor.temperature_2
    away_temp: 15
    min_temp: 15
    max_temp: 25
    hot_tolerance: 1
    cold_tolerance: 0.5
  - platform: generic_thermostat
    name: Bathroom Heating
    heater: switch.osram_plug_4
    target_sensor: sensor.temperature_7
    away_temp: 15
    min_temp: 15
    max_temp: 25
    hot_tolerance: 1
    cold_tolerance: 0.5