default_config:

http:
  base_url: ***REMOVED***
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:restart
  heating_timer:
    name: Use heating timer
    icon: mdi:toggle-switch

tuya:
  username: !secret tuya_login
  password: !secret tuya_password
  country_code: 420
  platform: smart_life

google_assistant:
  project_id: ***REMOVED***
  entity_config:
    group.all_automations:
      expose: false

notify:
  - name: html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - name: all
    platform: group
    services:
      - service: html5
        data:
          target: ['x2pro', 'n550']
      - service: ios
        data:
          target: 'ios_i7sw'
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

ios:

asuswrt:
  host: !secret asuswrt_host
  username: !secret asuswrt_username
  ssh_key: /ssl/asuswrt_ssh
  sensors:
    - download_speed
    - upload_speed

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

logger:
  default: warning
history:
recorder:
  db_url: sqlite:////tmp/home-assistant_v2.db

frontend:
  themes: !include themes.yaml

climate:
  - platform: generic_thermostat
    name: Room Heating
    heater: switch.ikea_plug
    target_sensor: sensor.temperature_2
    away_temp: 15
    min_temp: 15
    max_temp: 25
    hot_tolerance: 1
    cold_tolerance: 1
  - platform: generic_thermostat
    name: Bathroom Heating
    heater: switch.osram_plug_4
    target_sensor: sensor.temperature_7
    away_temp: 15
    min_temp: 15
    max_temp: 25
    hot_tolerance: 1
    cold_tolerance: 1

input_number:
  target_temp_room_high:
    name: Room High Target Temperature
    min: 15
    max: 25
    step: 0.5
    unit_of_measurement: '*C'
    icon: mdi:arrow-top-right-thick
  target_temp_room_low:
    name: Room Low Target Temperature
    min: 15
    max: 25
    step: 0.5
    unit_of_measurement: '*C'
    icon: mdi:arrow-bottom-right-thick
  target_temp_bathroom_high:
    name: Bathroom High Target Temperature
    min: 15
    max: 25
    step: 0.5
    unit_of_measurement: '*C'
    icon: mdi:arrow-top-right-thick
  target_temp_bathroom_low:
    name: Bathroom Low Target Temperature
    min: 15
    max: 25
    step: 0.5
    unit_of_measurement: '*C'
    icon: mdi:arrow-bottom-right-thick
    
  light_step:
    name: 'Step the lights this much'
    initial: 20
    min: 1
    max: 64
    step: 1
  light_minimum:
    name: 'No dimmer than this'
    initial: 5
    min: 1
    max: 255
    step: 1
  light_maximum:
    name: 'No brighter than this'
    initial: 255
    min: 50
    max: 255
    step: 1

input_datetime:
  weekday_start:
    name: Week day morning
    has_time: true
  weekday_end:
    name: Week day night
    has_time: true
  weekend_start:
    name: Weekend morning
    has_time: true
  weekend_end:
    name: Weekend night
    has_time: true

sensor:
  - platform: time_date
    display_options:
      - 'time'