default_config:

http:
  base_url: ***REMOVED***
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:restart
  heating_timer:
    name: Heating timer
    icon: mdi:toggle-switch

tuya:
  username: !secret tuya_login
  password: !secret tuya_password
  country_code: 420
  platform: smart_life

google_assistant:
  project_id: ***REMOVED***
  entity_config:
    group.all_automations:
      expose: false

notify:
  - name: html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - name: all
    platform: group
    services:
      - service: html5
        data:
          target: ['x2pro', 'n550']
      - service: ios
        data:
          target: 'ios_i7sw'
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

ios:

asuswrt:
  host: !secret asuswrt_host
  username: !secret asuswrt_username
  ssh_key: /ssl/asuswrt_ssh
  sensors:
    - download_speed
    - upload_speed

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

logger:
  default: warning
history:
recorder:
  db_url: sqlite:////tmp/home-assistant_v2.db

frontend:
  themes: !include themes.yaml

climate:
  - platform: generic_thermostat
    name: Heating
    heater: switch.ikea_plug
    target_sensor: sensor.temperature_2
    min_temp: 10
    max_temp: 25
    ac_mode: false
    hot_tolerance: 1
    cold_tolerance: 1
    min_cycle_duration:
      minutes: 1

input_number:
  heating_temperature:
    name: Temperature
    min: 10
    max: 25
    step: 0.5
    icon: mdi:thermometer

sensor:
  - platform: time_date
    display_options:
      - 'time'

input_datetime:
  weekday_morning_start:
    name: Week day morning start
    has_time: true
    has_date: false
  weekday_morning_stop:
    name: Week day morning stop
    has_time: true
    has_date: false
  weekend_morning_start:
    name: Weekend morning start
    has_time: true
    has_date: false
  weekend_morning_stop:
    name: Weekend morning stop
    has_time: true
    has_date: false
  weekday_evening_start:
    name: Week day evening start
    has_time: true
    has_date: false
  weekday_evening_stop:
    name: Week day evening stop
    has_time: true
    has_date: false
  weekend_evening_start:
    name: Weekend evening start
    has_time: true
    has_date: false
  weekend_evening_stop:
    name: Weekend evening stop
    has_time: true
    has_date: false